<?php
return array (
  1 => 
  array (
    'siteid' => '1',
    'name' => '默认站点',
    'dirname' => '',
    'domain' => 'http://localhost/php/university/',
    'site_title' => 'PHPCMS演示站',
    'keywords' => 'PHPCMS演示站',
    'description' => 'PHPCMS演示站',
    'release_point' => '',
    'default_style' => 'default',
    'template' => 'default',
    'setting' => '{"upload_maxsize":"2048","upload_allowext":"jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf","watermark_enable":"1","watermark_minwidth":"300","watermark_minheight":"300","watermark_img":"statics\\/images\\/water\\/\\/mark.png","watermark_pct":"85","watermark_quality":"80","watermark_pos":"9"}',
    'uuid' => 'e0ae6251-a25c-11e6-87c5-d8cb8a7cc58e',
    'url' => 'http://localhost/php/university/',
  ),
  2 => 
  array (
    'siteid' => '2',
    'name' => '测试',
    'dirname' => 'test',
    'domain' => 'http://localhost/php/university/',
    'site_title' => '测试子站点',
    'keywords' => '子站点',
    'description' => '子站点',
    'release_point' => '',
    'default_style' => 'default1',
    'template' => 'default1',
    'setting' => '{"upload_maxsize":"2000","upload_allowext":"jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf","watermark_enable":"0","watermark_minwidth":"300","watermark_minheight":"300","watermark_img":"statics\\/images\\/water\\/http:\\/\\/localhost\\/php\\/university\\/mark.gif","watermark_pct":"100","watermark_quality":"80","watermark_pos":"9"}',
    'uuid' => '',
    'url' => 'http://localhost/php/university/',
  ),
  3 => 
  array (
    'siteid' => '3',
    'name' => '默认模板',
    'dirname' => 'moren',
    'domain' => 'http://localhost/php/university/',
    'site_title' => '默认模板',
    'keywords' => '默认模板',
    'description' => '默认模板',
    'release_point' => '',
    'default_style' => 'default_bak',
    'template' => 'default_bak',
    'setting' => '{"upload_maxsize":"2000","upload_allowext":"jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf","watermark_enable":"0","watermark_minwidth":"300","watermark_minheight":"300","watermark_img":"http:\\/\\/localhost\\/php\\/university\\/statics\\/images\\/water\\/mark.gif","watermark_pct":"100","watermark_quality":"80","watermark_pos":"9"}',
    'uuid' => '',
    'url' => 'http://localhost/php/university/',
  ),
  4 => 
  array (
    'siteid' => '4',
    'name' => '武汉子站',
    'dirname' => 'zizhan',
    'domain' => 'http://localhost/php/university/html/zizhan/',
    'site_title' => '子站',
    'keywords' => '子站',
    'description' => '子站',
    'release_point' => '',
    'default_style' => 'zizhan_default',
    'template' => 'zizhan_default',
    'setting' => '{"upload_maxsize":"2000","upload_allowext":"jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf","watermark_enable":"0","watermark_minwidth":"300","watermark_minheight":"300","watermark_img":"statics\\/images\\/water\\/http:\\/\\/localhost\\/php\\/university\\/mark.gif","watermark_pct":"100","watermark_quality":"80","watermark_pos":"9"}',
    'uuid' => '',
    'url' => 'http://localhost/php/university/html/zizhan/',
  ),
);
?>